openapi: 3.0.0
info:
  title: Fuel Rats API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ./models/user.v1.json
                  meta:
                    $ref: ./models/searchmeta.v1.json
                  links:
                    type: string
                  included:
                    type: string
components:
  schemas: {}
